name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Tests
        run: yarn test
